# Mosa[Fl]ickaRator v0.9 configuration file.

### flickr conf (optional)
## Fkickr API key of this application
apiKey=a1dc81a91d6f5d5f4654f15ccd555bb9
## the secret
secret=7d57871c491751ae
## your username
user=13137552@N00
## the directory where user authentication information is stored.
authStoreDir=fickr.auth
## These are Set names to be downloaded
#downloadSets=Black and White
## Size can be {LARGE|MEDIUM|ORIGINAL|SMALL|SQUARE|THUMB}
flickrDownloadSize=MEDIUM
#
# mosaic conf
# width/height of tiles, images will be rescaled to this width/height
defaultTileWidth=200
defaultTileHeight=300
placementBlur=0
# horizontal/vertical tilecount. The number of tiles will be a multiple of thiese numbers
defaultHorizontalTileCount=19
defaultVerticalTileCount=4

# BW | RGB
targetImageType=RGB
# Shuffle the collection?
shuffleEnabled=true
# If tiles are missing to fill up the entire image, shall images from the
# collection be taken to fill up the image? If not - colored tiles will be generated.
fillUpMissingTilesWithImages=false
#bgColor
backgroundColor=#FF0000
#tiles color
tilesColorRange=#FF4F00-#FFBF00,#FFA500-#FFC520
#image filling strategy (NORMAL | CIRCLE)
imageFillingType=CIRCLE

#--- done setup
NORMAL_CLASS=jpeg.imagefiller.SimpleImageFillingStrategy
CIRCLE_CLASS=jpeg.imagefiller.CircleImageFillingStrategy